channels:
  targets:
  - [guyer, main]
travis:
  secure:
    BINSTAR_TOKEN: Hcp2dn0qesnIF96bMDicYt/Vb/qcog58qhSluEcSV3X9zw7vJF8nQjmte/ctJRAj7p4Hq1M/UjJnlzen0kxEqKDxHxIC+NmWeea5LG8jFyeRqUR0TXG52xcOvXVi5ae4JQJCy08zrbpE/EUtycZ6OFkEOEheOC4AH1GgWsQBsRDH2Wpk1hQtnFF0WNpVoAgdtqrq+txeunn6BQdN9ECILvEzuPioj31kfnAoIukCDat1Ws6y63uzuxPnd52cuUCtPcd840aWanWRs97FSaiRLjdBiJUygAIQQWVFe2oqFawx7sjACQ6urzhRNeIRpPiE+fKMI/f98zc5KOHVNxLAweNxLaJZ8BnhhLn7VWVpOi40EDG8qikCgeOcGKZLIzn8a8/tBdWX7dK23iHXNGQkuc3nqT8k2HNydKx0twWlPsr9NuFTz4JGJA6OvtGUVo/1s77WSDauPYUdYLWxQ1hQnnF6F2MZEwq5LXgZ3fo1gm86/x+ROQfIUO4ma4RojkdxvlqXuQviT0sQjH8Ov9wydhU68A53X22QnaAvPsI2I0wsPUz0N3EoAWsC5yf0x0PgwJLZr0sL3dCdhgGZuumA8hP5qvHHenah0G1jlFPdc1zxWQZDotIL+DA/p8L7NAZ9t4aJjVgrgsYEQjMD6nfgcbyScpbK1Y2KBR2MNCjXLCE=

appveyor:
  secure:
    BINSTAR_TOKEN: X89+MTZivHBAXLSEy/G8CnQu+orYtiX/vKbQ7w7Wqbhv11U+EPgW+otnBaeJ6JCY
# dummy
