channels:
  targets:
  - [guyer, main]

travis:
  secure:
    BINSTAR_TOKEN: Or2R/C+FbGphl9dxna+39EoYu77i/heatA8j5vyLf2dFjrmpAgiwPU9428BAlq+kgprF8KDejEym3S4p6EjuHrAr+uLwSduPWsWVKGHw/82aHzYdPKS8Vh5u/JkY0Gk8gW4OYqDlJBOlfwah+HS9PBvMWUg/ZJ8fIHgF9Sq6OIb8geEA2kCVindX+wjo3YVmkh5XnqOpk3i6XAGPXBHJplOxDEAG0jZSQnTt6L4yqkZHRDnitog27vgPyVUYZGg19+SKuxVEcj4O1ThWvIRkNWD9pn7Hkxf1twCwOVIsa28knlvNNNUz2DyxAAyZL8Hy1bRtS8ZJcQ5rfHrGxkbW4NmnTgyH9oRbMAdQWyHgBS/xUlyDiAf2PSGZ7ioBUgQfjvyMi6Up8PaOTfFCwexAdGOj/iQHCzrqZTmxwasM4DV9A1YnJjrUc2LMR3jmZ3VUx05fvlbvULhOxF8nZt82yDj+LrfuhWwDJ0an/u+c13WM8wLRbqx2e5rQ8ZavE9ClpbOdrxvBzNNi8v1X9TJAjlvYE4eFg1RSF4PGRIIidnPpopGvTD9piysW3FwU4S/+7uA4aKWzMsGLIeqW9ShyMRcRrtzjXvUVlw8oqnYDjJ2rB+TEE4i1NkKlLVPcW+DA76bqELgvKYysqBmaxESAT0Wyl4Ox7t4DFCj4GbUu5EU=
appveyor:
  secure:
    BINSTAR_TOKEN: 26P3JkJ/iVPaW6c+5V5XYJ6H9Jaw/iYr0SU7KqDJCRk2+ScBP0rsvIyDOxDE9let
